// List of panels: the names that appear in the GP UI
std::vector<std::string> panelNames = {"Global Panel"};

// XML for the default included panels
std::vector<std::string> panelXML = { 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
""
"<RACKUNIT size=\"10\" style=\"1024\" color=\"ff000000\" ver=\"5.0\">"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.07249626307922272\" y=\"0.6043478260869565\""
"          width=\"0.1300448430493273\" height=\"0.4521739130434783\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Display\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.3269230769230769\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"11\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DISPLAY\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.2787742899850523\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"1\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS1\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.336322869955157\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"2\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS2\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.3938714499252616\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"3\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS3\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.4506726457399103\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"4\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS4\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.5082212257100149\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"5\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS5\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.5657698056801196\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"6\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS6\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.6233183856502242\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"7\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"15424\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS7\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.6801195814648729\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"8\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS8\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.5369955156950673\" y=\"0.2065217391304348\""
"          width=\"0.5687593423019432\" height=\"0.2130434782608696\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Direct Select\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"1\" overrideName=\"1\""
"          captionVisible=\"0\" captionHeight=\"0.2857142857142857\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\" backPlate=\"10\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DIRECT_SELECT_LABEL\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.8849028400597907\" y=\"0.2065217391304348\""
"          width=\"0.1046337817638266\" height=\"0.2130434782608696\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Bank\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"1\" overrideName=\"1\""
"          captionVisible=\"0\" captionHeight=\"0.3061224489795918\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\" backPlate=\"10\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.8561285500747384\" y=\"0.5804347826086956\""
"          width=\"0.05455904334828102\" height=\"0.4739130434782609\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Up\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"15424\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_BANKUP\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.9136771300448431\" y=\"0.5804347826086956\""
"          width=\"0.05455904334828102\" height=\"0.4739130434782609\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Down\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_BANKDOWN\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.07511210762331838\" y=\"0.2065217391304348\""
"          width=\"0.1038863976083707\" height=\"0.2130434782608696\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Grid Selector\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"1\" overrideName=\"1\""
"          captionVisible=\"0\" captionHeight=\"0.3061224489795918\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\" backPlate=\"10\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.7380418535127056\" y=\"0.5847826086956521\""
"          width=\"0.05455904334828102\" height=\"0.4739130434782609\" sendScaledValueChangedOnly=\"0\""
"          caption=\"9\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"15424\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS9\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.7955904334828101\" y=\"0.5847826086956521\""
"          width=\"0.05455904334828102\" height=\"0.4739130434782609\" sendScaledValueChangedOnly=\"0\""
"          caption=\"10\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS10\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.1894618834080717\" y=\"0.2065217391304348\""
"          width=\"0.1038863976083707\" height=\"0.2130434782608696\" sendScaledValueChangedOnly=\"0\""
"          caption=\"View/Mode\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"1\" overrideName=\"1\""
"          captionVisible=\"0\" captionHeight=\"0.3061224489795918\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\" backPlate=\"10\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.1907276995305164\" y=\"0.5939597315436241\""
"          width=\"0.08098591549295775\" height=\"0.4496644295302014\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Toggle\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2835820895522388\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_MODE\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"</RACKUNIT>"
};