// List of panels: the names that appear in the GP UI
std::vector<std::string> panelNames = {"Global Panel"};

// XML for the default included panels
std::vector<std::string> panelXML = { 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
""
"<RACKUNIT size=\"10\" style=\"1024\" color=\"ff000000\" ver=\"5.0\">"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.08146487294469357\" y=\"0.6043478260869565\""
"          width=\"0.1300448430493273\" height=\"0.4521739130434783\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Display\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.3269230769230769\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"11\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DISPLAY\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.1907276995305164\" y=\"0.5805369127516778\""
"          width=\"0.05516431924882629\" height=\"0.4765100671140939\" sendScaledValueChangedOnly=\"0\""
"          caption=\"1\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS1\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.2481315396113603\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"2\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS2\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.3056801195814648\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"3\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS3\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.3624813153961136\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"4\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS4\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.4200298953662182\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"5\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS5\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.4775784753363229\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"6\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS6\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.5351270553064275\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"7\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"15424\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS7\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.5919282511210763\" y=\"0.5826086956521739\""
"          width=\"0.05530642750373692\" height=\"0.4782608695652174\" sendScaledValueChangedOnly=\"0\""
"          caption=\"8\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS8\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.4488041853512705\" y=\"0.2065217391304348\""
"          width=\"0.5687593423019432\" height=\"0.2130434782608696\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Direct Select\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"1\" overrideName=\"1\""
"          captionVisible=\"0\" captionHeight=\"0.2857142857142857\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\" backPlate=\"10\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DIRECT_SELECT_LABEL\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.8183856502242153\" y=\"0.2065217391304348\""
"          width=\"0.1046337817638266\" height=\"0.2130434782608696\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Bank\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"1\" overrideName=\"1\""
"          captionVisible=\"0\" captionHeight=\"0.3061224489795918\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\" backPlate=\"10\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.7896113602391629\" y=\"0.5804347826086956\""
"          width=\"0.05455904334828102\" height=\"0.4739130434782609\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Up\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"15424\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_BANKUP\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.8471599402092675\" y=\"0.5804347826086956\""
"          width=\"0.05455904334828102\" height=\"0.4739130434782609\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Down\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_BANKDOWN\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.08408071748878924\" y=\"0.2065217391304348\""
"          width=\"0.1038863976083707\" height=\"0.2130434782608696\" sendScaledValueChangedOnly=\"0\""
"          caption=\"Grid Selector\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"1\" overrideName=\"1\""
"          captionVisible=\"0\" captionHeight=\"0.3061224489795918\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"4\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\" backPlate=\"10\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.6498505231689088\" y=\"0.5847826086956521\""
"          width=\"0.05455904334828102\" height=\"0.4739130434782609\" sendScaledValueChangedOnly=\"0\""
"          caption=\"9\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"15424\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS9\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.7073991031390134\" y=\"0.5847826086956521\""
"          width=\"0.05455904334828102\" height=\"0.4739130434782609\" sendScaledValueChangedOnly=\"0\""
"          caption=\"10\" captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\""
"          hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2333333333333333\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\" backPlate=\"7\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GPGS_DS10\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\""
"          btnRadioGroupIndex=\"0\" btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"</RACKUNIT>"
};